version: '3.8'
services:
  # database
  mongo:
    image: mongo:8.0.5
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - app_network
    volumes:
      - ./mongo_data:data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    depends_on:
      - mongo
    networks:
      - app_network

  # App services
  app:
    container_name: ${APP_NAME:-quiz_code_camp_api}
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - env.example.dev
    ports:
      - ${APP_PORT:-8080}:${APP_PORT:-8080}
    depends_on:
      - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
volumes:
  mongo_data:
