version: '3.8'
services:
  # database
  database:
    image: mongo:8.0.5
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoguy
      - MONGO_INITDB_ROOT_PASSWORD=mongodb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoguy
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongoguy:-mongodb@database:27017/admin?authSource=admin
